### ISSUE TITLE
File name cannot contain certain characters

### ISSUE THREAD

**Issue by kmaustral** [joelseq/obsidian-linkstowr#3]
A recent sync has failed. Looking at the console, it seems to be an issue with characters in the note title:

> Failed to create file: The Flavour of Green Tea Over Rice review – Ozu's bittersweet triumph | Drama films | The Guardian Error: File name cannot contain any of the following characters: * " \ / < > : | ?

**Comment by joelseq** [comment]
Thanks for reporting this issue! This is a bit tricky to handle and I was wondering what you think the desired behavior here would be? Would you prefer it to fail at the time of trying to save the link within the Chrome extension popup window or just auto-remove the invalid characters at the time of saving the file in Obsidian.

**Comment by kmaustral** [comment]
Hi Joel. I think auto-removing the invalid characters would be best. I
think Readwise replaces ":" with "-", but simply deleting is fine.
Otherwise, there would be no way to bookmark a file with these characters
in the title.

Because there is one invalid file, I can't bookmark any other file at the
moment. The process is stuck.

Let me know if there is anything else I can explore.

Kevin

**Comment by joelseq** [comment]
Hi Kevin, sorry it took me a while to get to this. I just tried to repro this using the title that you provided and it managed to create the file successfully for me. I realized that the code is already supposed to remove the illegal file name characters [[link to code](https://github.com/joelseq/obsidian-linkshelf/blob/main/src/main.ts#L97C28-L97C68)]. Do you know if there were any more characters in the title than what's mentioned in your first comment ("The Flavour of Green Tea Over Rice review – Ozu's bittersweet triumph | Drama films | The Guardian")?

**Comment by kmaustral** [comment]
Here's the console report:
![image](https://github.com/joelseq/obsidian-linkshelf/assets/73867063/2496254c-cac3-40bb-83f5-97cd0d8e0db7)

Is there a way of clearing the queue so I can start again?

**Comment by joelseq** [comment]
The easiest way to get unblocked would be to create a new account as you just need a username for it. 

I'll try to dig in a bit further to see what's going on here so that once the issue is resolved you can sync all your currently failing ones!

**Comment by joelseq** [comment]
I just published a new release v0.2.3 which removes the "|" character as well (it wasn't previously being removed). Can you try to see if that resolved the issue for you?

**Comment by kmaustral** [comment]
Great. That's solved the problem!
