### ISSUE TITLE
LinkStowr Sync failed

### ISSUE THREAD

**Issue by GLyttek** [joelseq/obsidian-linkstowr#9]
Hi all, my LinkStowr suddenly is also experiencing the issue that Sync to Obsidian is failing. Worked fine for about two days and now has stopped working.

**Comment by joelseq** [comment]
Hi @GLyttek, can you confirm if the access token that you added to the LinkStowr settings in Obsidian is correct? It should be of the format `lshelf_XXXXXXXX_XXXXXXXXXXXXX`. If that doesn't work can you try creating a new access token and using that instead?

**Comment by GLyttek** [comment]
Hi @joelseq , yes I can confirm, that I have added the correct token. I also have created a new one today and entered that into Obsidian. 
I however have not deleted the old Token. Should I try to do that? I am also not sure, what might happen if I remove and re-add the add-on.

![image](https://github.com/joelseq/obsidian-linkstowr/assets/107279662/af1008fe-1811-430d-a5a2-05a4c73dfe4d)

**Comment by joelseq** [comment]
Have you tried syncing with the new token? I don't see any error logs showing up so I'm not sure if it's an issue with the linkstowr API or the obsidian plugin. One thing you can try is to check the console (cmd+option+i on macOS or ctrl+shift+i on Windows) and see if there are any errors showing up there

**Comment by GLyttek** [comment]
Hi @joelseq , Thank you for the steps, he seems to fail on the creation of the File. 
I am still not sure, to why, as I haven't changed anything on my Linux System.

![image](https://github.com/joelseq/obsidian-linkstowr/assets/107279662/1e9ebd5d-e93c-417b-949b-7f89fe8b7b09)

![image](https://github.com/joelseq/obsidian-linkstowr/assets/107279662/73458f47-b172-43b3-8528-969c13d7bcbd)

**Comment by GLyttek** [comment]
Hi @joelseq , Thank you for your help! I moved the Folder back up the structure, and it works now again.

**Comment by joelseq** [comment]
@GLyttek great to here! I think I can potentially make some UX improvements to show an alert or something when it fails due to the folder not existing

**Comment by GLyttek** [comment]
That would be nice. 
Even due I am not 100% clear, why it first worked, maybe something with the links I ingested.

But the important thing is, that it works again and hasn't lost any links.  So I am a happy customer. :-) 

Maybe it is because of my folder structure,where the Links folder was on the 4th level in the tree structure and now is back the third and working.
                 
                 
  Thanks a Million @joelseq !
